CREATE TABLE TB_CLIENTE (
    ID_CLIENTE      NUMBER          NOT NULL,
    NOME            VARCHAR2(100)   NOT NULL,
    EMAIL           VARCHAR2(100)   NOT NULL,
    CEP             VARCHAR2(8),
    LOGRADOURO      VARCHAR2(150),
    BAIRRO          VARCHAR2(100),
    CIDADE          VARCHAR2(100),
    UF              CHAR(2)         NOT NULL,
    ATIVO           NUMBER(1)       DEFAULT 1,
    -- CORRIGIDO: DEFAULT SYSTIMESTAMP adicionado de volta
    DT_CRIACAO      DATE       DEFAULT SYSDATE NOT NULL, 
    DT_ATUALIZACAO  DATE,

    -- Constraints
    CONSTRAINT PK_TB_CLIENTE PRIMARY KEY (ID_CLIENTE),
    CONSTRAINT UQ_TB_CLIENTE_EMAIL UNIQUE (EMAIL),
    CONSTRAINT CK_TB_CLIENTE_UF CHECK (UF IN (
        'AC', 'AL', 'AP', 'AM', 'BA', 'CE', 'DF', 'ES', 'GO', 'MA',
        'MT', 'MS', 'MG', 'PA', 'PB', 'PR', 'PE', 'PI', 'RJ', 'RN',
        'RS', 'RO', 'RR', 'SC', 'SP', 'SE', 'TO'
    )),
    CONSTRAINT CK_TB_CLIENTE_ATIVO CHECK (ATIVO IN (0, 1))
);

CREATE INDEX IDX_CLIENTE_NOME ON TB_CLIENTE (NOME);
CREATE INDEX IDX_CLIENTE_NOME_EMAIL ON TB_CLIENTE (EMAIL);
CREATE INDEX IDX_CLIENTE_NOME_EMAIL ON TB_CLIENTE (NOME, EMAIL);