CREATE TABLE TB_LOG_ERRO (
    
    ID_LOG        NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
    DT_EVENTO     DATE,   
    USUARIO       VARCHAR2(50) NOT NULL,    
    ORIGEM        VARCHAR2(100),    
    MENSAGEM      VARCHAR2(4000) NOT NULL,    
    CODIGO_ERRO   VARCHAR2(20),    
    CONSTRAINT TB_LOG_ERRO_PK PRIMARY KEY (ID_LOG)
);

-- Comentários (Opcional, mas Altamente Recomendado)
COMMENT ON TABLE TB_LOG_ERRO IS 'Registro centralizado de erros da aplicação para monitoramento e auditoria.';
COMMENT ON COLUMN TB_LOG_ERRO.ID_LOG IS 'Chave primária e sequencial para o registro de log.';
COMMENT ON COLUMN TB_LOG_ERRO.DT_EVENTO IS 'Data e hora em que o erro foi registrado.';
COMMENT ON COLUMN TB_LOG_ERRO.USUARIO IS 'Usuário da sessão que gerou o erro.';
COMMENT ON COLUMN TB_LOG_ERRO.ORIGEM IS 'Nome do módulo, trigger, ou procedure onde o erro ocorreu.';
COMMENT ON COLUMN TB_LOG_ERRO.MENSAGEM IS 'Descrição completa da mensagem de erro (SQLERRM ou Forms).';
COMMENT ON COLUMN TB_LOG_ERRO.CODIGO_ERRO IS 'Código de erro numérico (SQLCODE ou ORA-XXXXX).';

-- Exemplo de índice para buscas por data ou usuário (Opcional)
CREATE INDEX TB_LOG_ERRO_IDX1 ON TB_LOG_ERRO (DT_EVENTO);
CREATE INDEX TB_LOG_ERRO_IDX2 ON TB_LOG_ERRO (USUARIO);